name: mPublish -- No tests

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK via Eclipse Temurin
          java-version: '17'
      - name: Publish package
        run: ./mvnw -X -ntp -DskipTests --batch-mode deploy -Dusername=$GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
